import { StringMap } from "../types";

export const teamMap: StringMap = {
  PSG: "Paris",
  Koln: "FC Koln",
  "Bayern M.": "Bayern",
  "Bayern M. II": "Bayern",
  "Sporting L.": "Sporting Lisbon",
  "Atl. Madrid": "Atletico Madrid",
  "Ath. Bilbao": "Athletic Bilbao",
  "Greuther Furth": "SPVGG Greuther",
  "MK Dons": "Milton Keynes Dons",
  "Dep. La Coruna": "La Coruna",
  "Nott. Forest": "Nottingham Forest",
  "St. Etienne": "St Etienne",
  "Borussia M.": "Monchen",
  "Sparta R.": "Sparta",
  Brondby: "Brøndby",
  "Bodo/Glimt": "Bodø",
  "Eintracht F.": "Ein Frankfurt",
  "Dinamo Z.": "Dinamo Zagreb",
  "Slovan B.": "Slovan Bratislava",
  "Atl. Nacional": "Atletico Nacional",
  "Steaua B.": "Steaua Bucurest",
  "U. Craiova 1948": "Universitatea Craiova",
  "Atletico-MG": "Atletico MG",
  "Ull/Kisa": "Ull Kisa",
  Tirol: "WSG",
  Orebro: "Oerebro",
  "Lokomotiv M.": "Lok. Moscow",
  "Spartak M.": "Spartak Moscow",
  Rostov: "FK Rostov",
  Krasnodar: "FK Krasnodar",
  Basel: "FC Basel",
  "Lokomotiva Z.": "NK Lokomotiva",
  Haugesund: "FK Haugesund",
  Kobe: "Vissel",
  Iwata: "Jubilo",
  Partizan: "Partizan Belgrade",
  "Lommel Utd": "Lommel SK",
  "Dag & Red": "Dagenham",
  "Porto II": "Porto",
  "St. Mirren": "St Mirren",
  Zilina: "MSK Zilina",
  Plzen: "Viktoria Plzen",
  "Ceske Budejovice": "Motor České",
  Aucas: "SD Aucas",
  Juarez: "FC Juarez",
  "La Guaira": "Real Esppor",
  Sarajevo: "FK Sarajevo",
  Voluntari: "FC Voluntari",
  Mioveni: "CS Mioveni",
  Trnava: "FC Spartak Trnava",
  Sered: "ŠKF Sereď",
  Dragovoljac: "Hrvatski Dragovoljac",
  Koge: "Køge",
  Helsingor: "FC Helsingoer",
  Volendam: "FC Volendam",
  "VVV Venlo": "Venlo",
  "Terengganu 2": "Terengganu",
  Oleksandriya: "FC Olexandria",
  "River Plate Asuncion": "Club River Plate Asunción",
  "Libertad Asuncion": "Club Libertad",
  "Ind. Medellin": "Independiente Medellín",
  "Termalica N.": "Nieciecza",
  "UC Dublin": "UCD",
  Horsens: "AC Horsens",
  Schweinfurt: "FC Schweinfurt",
  Amorebieta: "SD Amorebieta",
  "F. Dusseldorf": "Fortuna Düsseldorf",
  Cambuur: "SC Cambuur",
  Parma: "Parma Calcio 1913",
  "Brown Adrogue": "Brown de Adrogué",
  Buducnost: "Buducnost Podgorica",
  Guadalajara: "CD Guadalajara",
  Huila: "Atlético Huila",
  Zeledon: "Pérez Zeledón",
  "ADR Jicaral": "Jicaral",
  Santos: "Santos FC",
  Leczna: "Gornik Leczna",
  Heidenheim: "FC Heidenheim",
  "Guarani Asuncion": "Club Guaraní",
  Buchbach: "TSV Buchbach",
  Legnica: "Miedz Legnica",
  "R. Rzeszow": "Resovia Rzeszów",
  "Suwon Bluewings": "Suwon Samsung Bluewings",
  Senica: "FK Senica",
  Ried: "SV Josko Ried",
  Liefering: "FC Liefering",
  "Al Taawon": "Al-Taawon",
  "Al Raed": "Al-Raed",
  "Al Shabab Riyadh": "Al Shabab",
  Damac: "Dhamk",
  Dordrecht: "FC Dordrecht",
  Telstar: "SC Telstar",
  "RWDM Brussels": "Molenbeek",
  "W. Beveren": "Waasland-Beveren",
  "Stjordals Blink": "Stjørdals-Blink",
  "St. Albans": "St Albans City",
  "FC Juniors": "Lask Juniors Linz",
  "Vorwarts Steyr": "SK Vorwarts Steyr",
  "FAC Wien": "Floridsdorfer AC",
  Ahlen: "Rot Weiss Ahlen",
  "Koln II": "FC Koln",
  "Jong AZ Alkmaar": "AZ Alkmaar",
  "Austria V. II": "Austria Vienna",
  "Santos Laguna": "Santos",
  "Atletico San Luis": "Atletico de San Luis",
  "Cabinteely FC": "Cabinteely",
  "Proleter NS": "Proleter Novi Sad",
  "Werder II": "Werder",
  "RW Koblenz": "Rot-Weiß Koblenz",
  "Dalum IF": "Dalum",
  Bandirmaspor: "Bandırma BİK",
  Zwolle: "PEC Zwolle",
  Siena: "Robur Siena",
  Oss: "TOP Oss",
  Nordsjaelland: "FC Nordsjælland",
  "Dynamo M.": "Dinamo Moscow",
  Mjondalen: "Mjoendalen",
  "Akhmat Grozni": "Terek Grozny",
  "Metalist 1925": "FC Metalist Kharkiv",
  Nagasaki: "V-Varen Nagasaki",
  "CD Calahorra": "Calahorra",
  Juventus: "Juventus Women",
  Lillestrom: "Lillestroem",
  "Dnipro-1": "SC Dnipro-1",
  "M. Petach Tikva": "Maccabi Petach Tikva",
  "A. Klagenfurt": "Austria Klagenfurt",
  Naestved: "Næstved BK",
  Altach: "SC Rheindorf Altach",
  "Standard L.": "Standard Liege",
  "Seraing Utd": "RFC Seraing",
  Ferreira: "F.C. Paços de Ferreira",
  "LASK Linz": "LASK",
  Indija: "Inđija",
  "Din. Bucharest": "Dinamo Bucuresti",
  Stromsgodset: "Stroemsgodset",
  Saransk: "Mordovya",
  Rustavi: "Metalurgi Rustavi",
  "Kokand 1912": "Kokand-1912",
  "Sporting Gijon": "Sp Gijon",
  "Vizela U23": "Vizela",
  "Sheffield Utd U23": "Sheffield United",
  "Met. Bekobod": "Metalourg",
  Smyrnis: "Apollon Smirnis",
  "St. Patricks": "St Patricks",
  "Red Star 93": "Red Star",
  "Ind. Rivadavia": "Independiente Rivadavia",
  Riestra: "Deportivo Riestra",
  "Rapid B.": "Rapid Bucuresti",
  "Dep. Santamarina": "Santamarina",
  "RW Essen": "Rot-Weiss Essen",
  Homberg: "VfB Homberg",
  "Din. Brest": "Dynamo Brest",
  Slutsk: "FC Slutsk",
  Luzern: "Lucerne",
  Honved: "Kispest Honved",
  Sochi: "PFC Sochi",
  Ufa: "FC Ufa",
  Tobol: "FC Tobol",
  Seregno: "U.S.D. 1913 Seregno Calcio",
  Druids: "Newi Cefn Druids",
  Sapporo: "Hokkaido Consadole Sapporo",
  "Milan U19": "Milan",
  Admira: "FC Trenkwalder Admira",
  "A. Lustenau": "Austria Lustenau",
  Amstetten: "SKU Amstetten",
  Mura: "NŠ Mura",
  "Al Wahda (Abu Dhabi)": "Al Wahda",
  Kofu: "Ventforet Kofu",
  Pipinsried: "FC Pipinsried",
  Kusatsu: "Thespakusatsu Gunma",
  "Nacional Madeira": "CD Nacional de Madeira",
  Oviedo: "Real Oviedo",
  "Atletico FC": "Atlético Cali",
  "TZV Rep.Kosovo": "Kosovo",
  "GA Eagles": "Go Ahead Eagles",
  "Dover Ath.": "Dover",
  Oostende: "KV Oostende",
  Maribor: "NK Maribor",
  Sundsvall: "GIF Sundsvall",
  "MOL Fehervar": "Videoton FC Fehervar",
  Podbrezova: "FK Železiarne Podbrezová",
  "U. De Chile": "Universidad de Chile",
  "Atletico-PR": "Atletico PR",
  Brno: "Líšeň",
  "Gornik Z.": "Gornik Zabrze",
  "La Serena": "Deportes La Serena",
  "Univ. Craiova": "Universitatea Craiova",
  "Zulte-Waregem": "Waregem",
  Aluminij: "NK Aluminij",
  "F. Karagumruk": "Karagumruk",
  Vicenza: "L.R. Vicenza Virtus",
  Minaj: "Mynai",
  "Chapecoense-SC": "Chapecoense",
  "U. Catolica": "Universidad Católica",
  "Montevideo Wanderers": "Wanderers",
  "Liverpool M.": "Liverpool Montevideo",
  "H. Jerusalem": "Hapoel Jerusalem",
  Achnas: "Ethnikos Achna",
  "Sandecja Nowy S.": "Sandecja Nowy Sacz",
  "Sabah Baku": "Sabah FC",
  "Cardiff Metro.": "Cardiff Metropolitan University",
  Meppen: "SV Meppen",
  "Lok. Leipzig": "Lokomotive Leipzig",
  Ashdod: "FC Ashdod",
  "IK Shmona": "Hapoel Kiryat Shmona",
  Prijedor: "Rudar Prijedor"
};
